name: Auto Update Activation Code

on:
  schedule:
    - cron: '0 0 */3 * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-and-shorten:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: pip install requests

      - name: Run Generator and Shortener
        env:
          SHORTENER_API_KEY: ${{ secrets.SHORTENER_API_KEY }}
        run: python generate_code.py

      - name: Commit and Push Changes
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"
          git add activation.json code.txt
          git commit -m "Update code and link [skip ci]" || echo "No changes"
          git push
