name: Auto Update Activation Code

on:
  schedule:
    - cron: '0 0 */3 * *' # يعمل تلقائياً كل 3 أيام
  workflow_dispatch:      # يسمح لك بتشغيله يدوياً للتجربة

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: pip install requests

      - name: Run Script
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHORTENER_API_KEY: ${{ secrets.SHORTENER_API_KEY }}
          GIST_ID: ${{ secrets.GIST_ID }} # 🟢 أضف هذا السطر تحديداً
        run: python generate_code.py

      - name: Commit and Push
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"
          
          # أضفنا فقط activation.json لأن الكود الحقيقي أصبح في الـ Gist المخفي
          git add activation.json
          
          # لن نرفع ملفات txt هنا لكي لا يراها أحد، سنكتفي بتحديث الـ JSON
          git commit -m "Update activation hash and link [skip ci]" || echo "No changes to commit"
          git push
